#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

users:
  - name: polkadot
    gecos: Polkadot user

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - software-properties-common
  - p7zip-full
  - ntp
  - docker-ce
  - docker-ce-cli
  - docker-compose

ntp:
  enabled: true

# http://cloudinit.readthedocs.io/en/latest/topics/merging.html
# http://jen20.com/2015/10/04/cloudconfig-merging.html
merge_type: 'list(append)+dict(recurse_array)+str()'

