#cloud-config

runcmd:
  - mkdir /tmp/home && mv /home/* /tmp/home
  - umount /dev/sda
  - mkfs -t ext4 /dev/sda && mount /dev/sda /home
  - echo "/dev/sda /home ext4 rw,discard,errors=remount-ro 0 1" >> /etc/fstab
  - mv /tmp/home/* /home/

merge_type: 'list(append)+dict(recurse_array)+str()'
